language: node_js

node_js:
  - 9.11.1

sudo: required

addons:
  apt:
    packages:
      - sshpass

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test && yarn build

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
