language: node_js

node_js:
  - 9.11.1

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

test:
  - yarn test

script:
  - yarn build

deploy:
  provider: script
  script: bash yarn push
  on:
    branch: master
