language: node_js

node_js:
  - 9.11.1

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

install:
  - yarn

test:
  - yarn test

compile:
  - yarn build

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
