#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $DOCKER_USERNAME/invite:latest

echo "finished pushing image about to update server"
sshpass -p '$DEPLOY_PASS' ssh $DEPLOY_USER@$DEPLOY_HOST ~invite/update-invite
echo "finished updating server"
