#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $DOCKER_USERNAME/invite:latest

export SSHPASS=$DEPLOY_PASS
sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST ~invite/update-invite